FROM openjdk:11.0.2
ARG CONFLUENT_URL
ARG CONFLUENT_MAJOR_VERSION
ARG CONFLUENT_MINOR_VERSION
RUN curl -O $CONFLUENT_URL/$CONFLUENT_MAJOR_VERSION/confluent-$CONFLUENT_MINOR_VERSION.zip && unzip confluent-$CONFLUENT_MINOR_VERSION.zip && rm confluent-$CONFLUENT_MINOR_VERSION.zip
ENV PATH="${PATH}:/confluent-$CONFLUENT_MINOR_VERSION/bin"
WORKDIR /code/
